import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { LegalDocumentLayout } from "../components/legal/LegalDocumentLayout";
import { LEGAL_ENTITY, type LegalSectionDefinition } from "../lib/legal";

const P = ({ children }: { children: ReactNode }) => <p>{children}</p>;
const L = ({ items }: { items: string[] }) => <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>;

const sections: LegalSectionDefinition[] = [
  { id: "about-this-policy", title: "About This Policy", category: "Scope", content: <><P>{LEGAL_ENTITY.name} (Aurixa, we, us or our) is the organisation responsible for this Privacy Policy. It explains how we manage personal information across our website, applications, communications, onboarding and products and services.</P><P>Additional collection notices may apply at the point information is collected. Those notices should be read with this Policy.</P></> },
  { id: "information-we-collect", title: "Personal Information We Collect", category: "Information", content: <><P>The information we collect depends on how a person or organisation interacts with Aurixa. It may include:</P><L items={["Name, work email address, telephone number, organisation name, role or position and organisation type", "Approximate business or transaction volume, technology environment, workflow information and areas an organisation wishes to improve", "Information voluntarily entered into enquiry, application, onboarding or support fields", "Marketing communication preferences and records of correspondence", "Website usage and technical information needed to operate, understand and protect the website", "Account, platform, user permission, activity and support information where a service is used"]}/><P>Where a customer submits client, due-diligence or other materials through the platform, that information is customer-controlled platform data. The customer determines what is submitted and remains responsible for having authority to provide it.</P></> },
  { id: "how-we-collect", title: "How We Collect Information", category: "Collection", content: <><P>We collect information directly through website forms, priority-access or waitlist applications, correspondence, platform onboarding, account and platform use, and website or system activity.</P><P>Information may also be provided by an authorised representative of an organisation or by approved service providers supporting our operations.</P></> },
  { id: "why-we-use-information", title: "Why We Collect and Use Information", category: "Purpose", content: <><P>We collect and use information where reasonably required to operate Aurixa and manage our relationships.</P><L items={["Respond to enquiries, review applications and assess platform suitability", "Provide and administer services, accounts, billing and customer support", "Protect users and services, including security and fraud prevention", "Improve products, platform workflows and service quality", "Send optional marketing where a person has chosen to receive it", "Meet legal obligations and manage complaints, records and disputes"]}/></> },
  { id: "marketing", title: "Marketing Communications", category: "Choice", content: <><P>Marketing communications are optional. A person may withdraw consent or unsubscribe using the method provided in a message or by contacting Aurixa.</P><P>Withdrawing marketing consent does not prevent us from sending necessary service, security, account or operational communications.</P></> },
  { id: "cookies-technologies", title: "Cookies and Website Technologies", category: "Website", content: <><P>The website uses session storage to retain campaign attribution during a browsing session and to support controlled handoff and access flows for the readiness questionnaire. These records are used for website and application operation and are not persistent cookies.</P><P>Technologies used by particular Aurixa services may change. Where additional technologies materially affect personal information handling, we will provide appropriate information and update this Policy.</P></> },
  { id: "security", title: "How Information Is Held and Protected", category: "Safeguards", content: <><P>Information is held electronically using systems selected to support Aurixa operations. We apply reasonable technical and organisational safeguards, including access controls, user permissions, protected transmission and storage where supported, internal governance and incident response processes.</P><P>No electronic service can guarantee absolute security. Customers and users also have responsibilities for credential security, appropriate permissions and safe use of their systems.</P></> },
  { id: "disclosure", title: "Disclosure of Personal Information", category: "Recipients", content: <><P>We may disclose information where reasonably necessary to infrastructure and hosting providers, workflow and communication providers, customer-support or payment providers, and professional advisers. We may also disclose information to regulators, courts or law-enforcement bodies where authorised or required by law.</P><P>Information may be disclosed to participants and advisers in a proposed or completed business transfer, subject to appropriate safeguards.</P></> },
  { id: "overseas-disclosure", title: "Overseas Disclosure", category: "Data flows", content: <><P>Some providers supporting Aurixa may process or make information accessible outside Australia. Processing locations depend on the services and configurations in use.</P><P>Before making an overseas disclosure, Aurixa will consider the applicable legal requirements and reasonable safeguards. Current processing countries will be confirmed as part of the final legal and operational review.</P></> },
  { id: "retention", title: "Data Retention", category: "Lifecycle", content: <P>We retain personal information only for as long as reasonably required for its collection purpose, service administration, legal obligations, security, dispute resolution and recordkeeping. Retention depends on the nature of the information and applicable requirements. When information is no longer reasonably required, we take appropriate steps to delete or de-identify it, subject to lawful exceptions.</P> },
  { id: "access-correction", title: "Access and Correction", category: "Individual rights", content: <><P>A person may request access to personal information we hold about them or ask us to correct information that is inaccurate, out of date, incomplete, irrelevant or misleading through our <Link to="/contact">contact page</Link>.</P><P>We may need to verify identity before acting. We will assess and respond to requests in accordance with applicable law and explain where a request cannot be completed.</P></> },
  { id: "complaints", title: "Privacy Complaints", category: "Resolution", content: <><P>Privacy complaints may be submitted through our <Link to="/contact">contact page</Link>. Please describe the concern, the relevant interaction or information and the preferred contact method.</P><P>We will assess the complaint, seek further information where needed and communicate the outcome. Where available under applicable law, a person may also raise an unresolved complaint with the relevant external privacy regulator.</P></> },
  { id: "data-breaches", title: "Data Breaches", category: "Response", content: <P>Aurixa maintains processes to identify, assess and respond to suspected data breaches. We will take appropriate containment and remediation steps and provide notifications where legally required.</P> },
  { id: "third-party-links", title: "Third-Party Links and Services", category: "External services", content: <P>Our website and services may link to or integrate with third-party services. Those parties may maintain separate privacy practices and terms. Aurixa is not responsible for information handling outside the services it controls.</P> },
  { id: "children", title: "Children’s Privacy", category: "Audience", content: <P>Aurixa services are designed for business and professional use. They are not directed to children. If we become aware that personal information has been provided outside the intended business context, we will assess appropriate steps under applicable law.</P> },
  { id: "automated-decisions", title: "Automated Decision-Making", category: "Platform", content: <P>Aurixa uses structured workflows, calculations and analytical tools. Platform outputs depend on supplied information and require professional review. If functionality involving decisions with a significant effect on an individual is introduced, Aurixa will assess the applicable transparency and privacy requirements.</P> },
  { id: "changes", title: "Changes to This Policy", category: "Version control", content: <P>We may update this Privacy Policy to reflect changes to our practices, services or legal obligations. Material changes will be communicated appropriately, and the last-updated information will be revised when an approved version is published.</P> },
  { id: "contact-aurixa", title: "Contact Aurixa", category: "Enquiries", content: <><P>{LEGAL_ENTITY.name}<br/>ABN {LEGAL_ENTITY.abn}<br/>{LEGAL_ENTITY.location}</P><P>For privacy enquiries, access or correction requests and complaints, use the <Link to="/contact">Aurixa contact page</Link>.</P></> },
];

export default function PrivacyPolicy() { return <LegalDocumentLayout kind="privacy" eyebrow="Privacy & Information Governance" title="Privacy Policy" introduction="This Privacy Policy explains how Aurixa Systems Pty Ltd collects, holds, uses, discloses and protects personal information when individuals interact with the Aurixa website, submit an application, communicate with Aurixa or use Aurixa products and services." caption="PERSONAL INFORMATION LIFECYCLE" pageTitle="Privacy Policy | Aurixa Systems" description="Read the Aurixa Systems Privacy Policy and learn how personal information is collected, used, protected and managed." sections={sections} summary={<p>This working draft sets out the principles Aurixa applies to personal information and customer-controlled platform data. It is structured for transparency and is subject to final review and approval by Aurixa’s Australian legal adviser before publication.</p>} related={[{ label: "Terms and Conditions", to: "/terms-and-conditions" }, { label: "Compliance", to: "/compliance" }, { label: "Contact Aurixa", to: "/contact" }]}/>; }
