import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { LegalDocumentLayout } from "../components/legal/LegalDocumentLayout";
import { LEGAL_ENTITY, type LegalSectionDefinition } from "../lib/legal";

const P = ({ children }: { children: ReactNode }) => <p>{children}</p>;
const L = ({ items }: { items: string[] }) => <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>;
const sections: LegalSectionDefinition[] = [
  { id: "about-these-terms", title: "About These Terms", category: "Agreement", content: <><P>These Terms govern access to and use of the website, platform and related services supplied by {LEGAL_ENTITY.name} (Aurixa, we, us or our). An agreement is formed when an organisation accepts these Terms or an authorised user accesses a service under an applicable order.</P><P>An order form, subscription detail or enterprise agreement may add or vary terms. The final order of precedence between documents will be specified in the approved agreement.</P></> },
  { id: "eligibility-authority", title: "Eligibility and Authority", category: "Users", content: <><P>Each person accepting these Terms for an organisation represents that they have authority to bind that organisation. Information supplied during registration, procurement and use must be accurate, current and complete, and the services may be used only in a genuine business or professional capacity.</P><P>The subscribing organisation is responsible for selecting and supervising authorised users. A person without authority must not represent that an organisation has agreed to an order and should promptly notify Aurixa if access was created without proper approval.</P></> },
  { id: "accounts-access", title: "Accounts and Access", category: "Control", content: <><P>Account administrators must provide accurate registration details, allocate role-based access on a least-privilege basis and regularly review who can use the service. Credentials are personal to each authorised user and must not be shared, transferred or used to create a generic shared account unless Aurixa expressly supports that account type.</P><P>Customers are responsible for activity under accounts they administer except to the extent caused by Aurixa. They must promptly remove former personnel, update permissions when responsibilities change, and notify Aurixa of suspected compromise or unauthorised activity so that reasonable protective action can be coordinated.</P></> },
  { id: "subscriptions-orders", title: "Subscriptions, Plans and Orders", category: "Commercial", content: <P>Services may be supplied under subscription plans, seat limits, credits, usage allowances, order forms or additional service arrangements. The applicable order identifies the selected plan, included use, plan changes, taxes including GST, and any approved renewal structure.</P> },
  { id: "fees-payment", title: "Fees, Billing and Payment", category: "Commercial", content: <P>Fees, billing timing, payment requirements, renewal arrangements and any refund or late-payment rules are those set out in the applicable order or written agreement. Nothing in these Terms creates a charge or payment rule not disclosed before purchase.</P> },
  { id: "early-access", title: "Trials, Demonstrations and Early Access", category: "Pre-release", content: <><P>Trials, demonstrations and early-access features are provided for evaluation within the scope communicated by Aurixa. Access may be restricted, changed or ended, and pre-release functionality may be incomplete, unavailable or materially different from a production service.</P><P>Customers should not rely on evaluation services for critical operations or submit information that is inappropriate for the stated environment. Any special data, support or service limitations will be communicated with the relevant offer.</P></> },
  { id: "permitted-use", title: "Permitted Use", category: "Licence", content: <><P>Subject to the applicable plan or agreement, Aurixa grants authorised users a limited, non-exclusive and non-transferable right to access and use the service for the customer’s internal business purposes during the applicable service period.</P><P>Use must remain within applicable seat, credit, feature and usage allowances, comply with law and professional obligations, and include appropriate handling of client and other protected information.</P></> },
  { id: "prohibited-use", title: "Prohibited Use", category: "Controls", content: <><P>Users must not:</P><L items={["Use the service for illegal activity or infringe third-party rights", "Seek unauthorised access, conduct unapproved security testing or interfere with the platform", "Introduce malware or misuse confidential information", "Share credentials without authorisation or circumvent seat, credit or usage controls", "Misrepresent platform outputs, their source or their limitations", "Extract, reproduce or use platform materials to build a competing service except where law expressly permits"]}/></> },
  { id: "customer-data", title: "Customer Data", category: "Data rights", content: <><P>Customers retain their rights in data and materials they submit. Customers grant Aurixa only the rights reasonably required to provide, support, improve and secure the contracted service.</P><P>Customers must have authority to submit information and are responsible for lawful collection, instructions and accuracy. Personal information is handled in accordance with the <Link to="/privacy-policy">Privacy Policy</Link>.</P></> },
  { id: "privacy-security", title: "Privacy and Information Security", category: "Shared responsibility", content: <P>Aurixa applies reasonable safeguards within the services it controls. Customers remain responsible for their devices, credentials, authorised users, permissions, lawful instructions and exports. No service can guarantee absolute security. See our <Link to="/privacy-policy">Privacy Policy</Link> for information-handling details.</P> },
  { id: "compliance-workflows", title: "AML/CTF and Compliance Workflows", category: "Responsibility", content: <><P>Aurixa may provide workflow and record-management tools that support compliance activity. Aurixa does not guarantee compliance and does not replace legal, regulatory or professional advice.</P><P>Customers remain responsible for identifying and meeting their obligations, including their compliance programs, checks, professional decisions, recordkeeping and reporting.</P></> },
  { id: "platform-outputs", title: "Reports, Analytics and Platform Outputs", category: "Professional review", content: <><P>Reports, analytics and other outputs depend on the completeness and accuracy of supplied information, selected assumptions and configured workflows. Outputs may contain limitations or require contextual information that is not available to Aurixa.</P><P>Authorised users must review outputs, resolve apparent inconsistencies and apply appropriate professional judgement before relying on or communicating them. Outputs do not automatically constitute legal, financial, taxation, lending or investment advice, and the customer remains responsible for its final decisions and client recommendations.</P></> },
  { id: "third-party-services", title: "Third-Party Services and Integrations", category: "Integrations", content: <><P>Optional third-party services and integrations are governed by their providers’ separate terms, privacy practices, technical requirements and availability. The customer authorises data exchange when it enables an integration and is responsible for confirming that the connection is appropriate for its information and intended use.</P><P>Aurixa may change or discontinue an integration where its provider, security requirements or technical interface changes. Aurixa remains responsible for the parts of the service it controls, but cannot control an external provider’s availability or conduct.</P></> },
  { id: "intellectual-property", title: "Intellectual Property", category: "Ownership", content: <><P>Aurixa and its licensors retain rights in the platform, software, designs, methods, branding and service materials. Customers retain rights in customer data and customer materials.</P><P>Rights in generated reports, bespoke deliverables and feedback will be stated in the applicable order or approved agreement. No transfer of ownership is implied merely by access to the service.</P></> },
  { id: "confidentiality", title: "Confidentiality", category: "Mutual protection", content: <P>Each party must protect the other party’s confidential information using reasonable care, use it only for the agreement, and disclose it only to personnel and advisers who need it and are subject to appropriate duties. These obligations do not apply to information lawfully public, independently developed or lawfully received from another source. Legally required disclosure is permitted with notice where lawful.</P> },
  { id: "availability-changes", title: "Availability, Maintenance and Changes", category: "Operations", content: <P>Aurixa may perform maintenance and make reasonable changes as services evolve. We will communicate planned or material changes appropriately where they affect contracted use. Any specific service level or maintenance notice commitment must be recorded in the applicable agreement.</P> },
  { id: "suspension", title: "Suspension", category: "Protection", content: <P>Aurixa may proportionately suspend affected access where reasonably necessary to address a security threat, illegal use, material breach, applicable non-payment or risk to users or the platform. Where practicable, we will provide notice and an opportunity to remedy the issue.</P> },
  { id: "termination", title: "Termination and Cancellation", category: "Service end", content: <P>Termination, cancellation, notice, renewal and refund arrangements are governed by the applicable order or written agreement and rights that cannot be excluded by law. A party may have additional termination rights for an unremedied material breach.</P> },
  { id: "export-deletion", title: "Data Export and Deletion Following Termination", category: "Data lifecycle", content: <P>Available export arrangements and the handling of customer data following termination will be described in the applicable agreement and operational documentation. Aurixa may retain information where reasonably required by law, security, backup integrity, dispute management or recordkeeping obligations.</P> },
  { id: "consumer-guarantees", title: "Warranties and Consumer Guarantees", category: "Statutory rights", content: <P>Nothing in these Terms excludes, restricts or modifies a consumer guarantee, right or remedy that cannot lawfully be excluded. Any warranties and remedies for services will be interpreted subject to those protections and the applicable agreement.</P> },
  { id: "liability", title: "Liability", category: "Risk allocation", content: <P>Each party remains responsible for loss to the extent caused by its breach, negligence or unlawful conduct, subject to applicable law and the approved agreement. Any liability cap, excluded loss or allocation of responsibility must be expressly agreed and will not limit rights or liabilities that cannot lawfully be limited.</P> },
  { id: "indemnities", title: "Indemnities", category: "Risk allocation", content: <><P>Neither party is required to provide an indemnity unless it is expressly set out in an applicable order or written agreement. Any agreed indemnity must be interpreted in accordance with its stated scope, applicable law and the responsibility of each party for its own acts and omissions.</P><P>Nothing in these Terms creates a broad or unlimited indemnity, or removes a party’s obligation to take reasonable steps to reduce avoidable loss.</P></> },
  { id: "disputes", title: "Dispute Resolution", category: "Resolution", content: <P>A party raising a dispute should give written notice describing it. The parties will first seek resolution through good-faith discussion and internal escalation. If unresolved, they may agree to mediation before commencing court proceedings, except where urgent relief is reasonably required.</P> },
  { id: "governing-law", title: "Governing Law", category: "Jurisdiction", content: <P>The governing law and courts for an agreement are those identified in the applicable order or written agreement. Where that document confirms New South Wales, the laws of New South Wales, Australia apply and each party submits to the courts having jurisdiction there.</P> },
  { id: "changes-to-terms", title: "Changes to These Terms", category: "Version control", content: <P>Aurixa may update these Terms as services or legal requirements change. We will provide appropriate notice of material changes. A material change will take effect at the time stated in the notice, subject to the applicable agreement and law, rather than without notice.</P> },
  { id: "general", title: "General Provisions", category: "Administration", content: <><P>Neither party may assign the agreement except as permitted by the approved agreement or with appropriate consent. Invalid provisions are severed only to the extent required. A waiver must be clear and does not waive later rights.</P><P>The applicable documents form the entire agreement for their subject matter. Notices must use an approved channel. The parties are independent contractors. Neither party is responsible for delay caused by events beyond its reasonable control to the extent recognised by the agreement and law.</P></> },
  { id: "contact", title: "Contact", category: "Enquiries", content: <><P>{LEGAL_ENTITY.name}<br/>ABN {LEGAL_ENTITY.abn}<br/>{LEGAL_ENTITY.location}</P><P>For legal, account or service enquiries, use the <Link to="/contact">Aurixa contact page</Link>.</P></> },
];
export default function TermsAndConditions() { return <LegalDocumentLayout kind="terms" eyebrow="Platform Terms & Governance" title="Terms and Conditions" introduction="These Terms and Conditions govern access to and use of the Aurixa Systems website, platform and related services. They should be read together with the Privacy Policy, applicable order forms, subscription details and any additional written agreement entered into with Aurixa." caption="PLATFORM AGREEMENT FRAMEWORK" pageTitle="Terms and Conditions | Aurixa Systems" description="Read the terms governing access to and use of the Aurixa Systems website, platform and related services." sections={sections} summaryTitle="A Clear Framework for Responsible Platform Use." summary={<p>These Terms and Conditions establish the framework governing access to and use of the Aurixa Systems website, platform and related services. They define the responsibilities of Aurixa, subscribing organisations and authorised users while supporting secure, lawful and accountable platform use.</p>} related={[{ label: "Privacy Policy", to: "/privacy-policy" }, { label: "Compliance", to: "/compliance" }, { label: "Contact Aurixa", to: "/contact" }]}/>; }
