/**
 * Generate `public/sitemap.xml` and `public/llms.txt` from the route registry.
 *
 * Both files are derived data, not content: every URL in them comes from
 * `indexable: true` in `src/lib/routeMetadata.ts`. Writing them by hand is how
 * `/pricing-mock` — the page that charges real cards against the LIVE Stripe
 * account — would eventually end up published in a sitemap. Deriving them means
 * the leak can only happen by flipping a boolean that a test pins.
 *
 * Runs as `prebuild`, so `npm run build` (and therefore Vercel) always emits a
 * current pair. The output is committed as well, so it is reviewable in a diff
 * rather than appearing only inside a build; `routeMetadata.test.ts` fails if
 * the committed copy stops matching the registry.
 *
 *   npx tsx scripts/generate-seo-files.ts
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  DEFAULT_DESCRIPTION,
  SITE_ORIGIN,
  absoluteUrl,
  indexableRoutes,
} from "../src/lib/routeMetadata.ts";

const PUBLIC_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "public");

/**
 * `lastmod` is deliberately absent. It would move on every deploy whether or
 * not the page changed, and a `lastmod` that cannot be trusted is worse than no
 * `lastmod` at all — Google discounts the whole signal once it catches one
 * lying. `changefreq` is omitted for the same reason: it is documented as
 * ignored.
 */
function sitemap(): string {
  const urls = indexableRoutes()
    .map(
      (route) =>
        `  <url>\n` +
        `    <loc>${absoluteUrl(route.path)}</loc>\n` +
        (route.priority === undefined
          ? ""
          : `    <priority>${route.priority.toFixed(1)}</priority>\n`) +
        `  </url>`,
    )
    .join("\n");

  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/generate-seo-files.ts from src/lib/routeMetadata.ts.\n` +
    `     Do not edit by hand: run \`npm run build\` (or the script directly). -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${urls}\n` +
    `</urlset>\n`
  );
}

/**
 * llms.txt follows the llmstxt.org shape: an H1, a blockquote summary, then
 * link sections. Descriptions are the same strings the pages serve as their
 * meta description, so an assistant and a search engine are told the same
 * thing about each page.
 */
function llmsTxt(): string {
  const routes = indexableRoutes();
  const entry = (path: string) => routes.find((route) => route.path === path);

  const section = (heading: string, paths: string[]) => {
    const lines = paths
      .map((path) => {
        const route = entry(path);
        if (!route) return null;
        // The registry title carries the " | Aurixa Systems" suffix, which is
        // noise once the document is already headed "Aurixa Systems".
        const label = route.title.replace(/\s*\|\s*Aurixa Systems$/, "");
        return `- [${label}](${absoluteUrl(route.path)}): ${route.description}`;
      })
      .filter((line): line is string => line !== null);
    return lines.length ? `## ${heading}\n${lines.join("\n")}\n` : "";
  };

  return [
    `# Aurixa Systems`,
    ``,
    `> ${DEFAULT_DESCRIPTION}`,
    ``,
    `Aurixa Systems is an Australian company serving property, finance and`,
    `advisory firms. Access is granted through a staged Priority Access process`,
    `rather than self-serve signup, and pricing is not published on the public`,
    `site — the Contact page is the entry point for both.`,
    ``,
    section("Product", ["/platform", "/solutions", "/industries", "/docs"]),
    section("Company", ["/about", "/compliance", "/contact"]),
    section("Legal", ["/privacy-policy", "/terms-and-conditions"]),
    section("Optional", ["/resources", "/status"]),
  ].join("\n");
}

writeFileSync(join(PUBLIC_DIR, "sitemap.xml"), sitemap());
writeFileSync(join(PUBLIC_DIR, "llms.txt"), llmsTxt());

const count = indexableRoutes().length;
console.log(
  `generate-seo-files: ${count} indexable route${count === 1 ? "" : "s"} → ` +
    `public/sitemap.xml, public/llms.txt (origin ${SITE_ORIGIN})`,
);
